name: 'Setup Prism Dependencies'
description: 'Set Prisma in specified working directory'`gi

runs:
  using: "composite"
  steps:
    - run: sudo apt-get update -y && sudo apt-get install -y openssl
      shell: bash

    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
