name: 'Setup Prism Dependencies'
description: 'Set Prisma in specified working directory'

inputs:
  database_directory:
    required: true
    description: 'Directory containing the Prisma schema'

runs:
  using: "composite"
  steps:
    - run: sudo apt-get update -y && sudo apt-get install -y openssl
      shell: bash

    - uses: pnpm/action-setup@v3
      with:
        version: 8
        package_json_file: ${{ inputs.database_directory }}/package.json
        run_install:
          cwd: ${{ inputs.database_directory }}

    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: ${{ inputs.database_directory }}
