name: 'Setup Railway Environment'
description: 'Sets up the Railway environment'

inputs:
  railway_environment:
    required: true
    description: 'Railway environment name'

  railway_project_id:
    required: true
    description: 'Railway project ID'

  railway_database_name:
    required: true
    description: 'Name of the database to link'

  railway_api_token:
    required: true
    description: 'Railway API token'

runs:
  using: 'composite'
  steps:
    - uses : actions/setup-node@v4
      with:
        node-version: '20'

    - run: npm i -g @railway/cli

    - run: railway link --environment ${{ inputs.railway_environment }} ${{ inputs.railway_project_id }} ${{ inputs.railway_database_name }}
      env:
        RAILWAY_API_TOKEN: ${{ inputs.railway_api_token }}